### ISSUE TITLE
Is there anyway to stop webflow from loading this script on pages that dont have any ecommerce elements? Like the homepage for example

### ISSUE THREAD

**Issue by JakeLabate** [labate-group/Labate-Group-Private#2]
https://github.com/labate-group/Labate-Group-Website/blob/ed6e6db3679efc335f5f013d08f9851759e605c7/website.html#L303

**Comment by JakeLabate** [comment]
closeing - seems unlikely

**Comment by Rakibuzzaman47** [comment]
I couldn't find anything on this, if I had coding access I could have tried something.
