### ISSUE TITLE
Is there anything else that would make our robots.txt file better? What would make the ideal file?

### ISSUE THREAD

**Issue by JakeLabate** [labate-group/Labate-Group-Private#24]
https://github.com/labate-group/Labate-Group-Private/blob/c4d51d9de2df9feaa17e2db27a75b068d8238c5d/other-assets/robots.txt#L1

**Comment by Rakibuzzaman47** [comment]
I say it's already a standard one.

https://moz.com/learn/seo/robotstxt
https://www.contentkingapp.com/academy/robotstxt/
